version: "3"

services:
  miniservice:
    volumes:
      - "./service:/app"
    build:
      context: "./service"
      target: "development"
    ports:
      - "8080:8080"
      - "5678:5678" # debug
  redis:
    image: redis:latest
